# Generated by Django 5.2 on 2025-05-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('data', models.DateField()),
                ('especialidade', models.CharField(max_length=100)),
                ('observacoes', models.TextField(blank=True)),
            ],
        ),
    ]
