# Generated by Django 5.2 on 2025-05-07 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agendamento',
            new_name='Scheduling',
        ),
    ]
