# Generated by Django 5.2 on 2025-05-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('specialty', models.CharField(max_length=100)),
                ('observations', models.TextField(blank=True)),
            ],
        ),
    ]
